FichaCliente/Controllers/FichasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using FichaCliente.Models;
using FichaCliente.Scripts;
using Microsoft.Extensions.Caching.Memory;
using System.Globalization;

namespace FichaCliente.Controllers
{
    [Authorize]
    public class FichasController : Controller
    {
        Consultas QUERY = new Consultas();
        Procedimientos STORED = new Procedimientos();
        private readonly IMemoryCache _cache;

        public FichasController(IMemoryCache cache)
        {
            _cache = cache;
        }

        public void GetExtraCaja(string rec)
        {
            List<(string, string)> info = QUERY.GetEdad(rec);
            if (info.Count == 0)
            {
                ViewBag.edad = "";
                ViewBag.antiguedad = "Sin Fecha";
            }
            else
            {
                ViewBag.edad = Math.Round(Double.Parse(info[0].Item1, CultureInfo.GetCultureInfo("en-US")));
                ViewBag.antiguedad = info[0].Item2;
            }
        }

        public void GetExtraCartera(string rec)
        {
            List<(string, Int64)> info = QUERY.GetTelefono(rec);
            if (info.Count == 0)
            {
                ViewBag.direccion = "";
                ViewBag.telefono = "";
            }
            else
            {
                ViewBag.direccion = info[0].Item1;
                ViewBag.telefono = info[0].Item2;
            }
        }

        public void GetExtraRetencion(string rec)
        {
            string info = QUERY.consultaRetenciones(rec);
            if (info == "")
                info = "Sin retenciones";
            ViewBag.retenciones = info;
        }

        [HttpGet]
        public IActionResult Paneles(List<ModeloResumen>? clientes)
        {
            if (_cache.TryGetValue("KeyPanel", out List<ModeloResumen> recuperados))
            {
                clientes = recuperados;
                ViewData["titular"] = clientes.ElementAt(0).Nombre_Titular;
                ViewData["ci"] = clientes.ElementAt(0).Documento_de_Identidad;
                ViewData["titular"] = clientes.ElementAt(0).Nombre_Titular;
                _cache.Remove("KeyPanel");
            }
            else
            {
                clientes = clientes == null ? new List<ModeloResumen>() : clientes;
            }
            return View(clientes);
        }

        [HttpPost]
        public IActionResult Paneles(string DocId, string NomTit)
        {
            if (DocId == null)
                DocId = "-";
            if (NomTit == null)
                NomTit = "-";
            HttpContext.Session.SetString("CIsesion", DocId);
            HttpContext.Session.SetString("TITsesion", NomTit);
            List<ModeloResumen> panel = STORED.DatosCliente(DocId, NomTit);

            if (panel.FirstOrDefault() != null)
            {
                ViewData["ci"] = panel.ElementAt(0).Documento_de_Identidad;
                ViewData["titular"] = panel.ElementAt(0).Nombre_Titular;
            }
            else
            {
                ViewData["ci"] = "";
                ViewData["titular"] = "";

            }
            if (panel.Count == 0)
                ViewData["alert"] = true;
            else
                ViewData["alert"] = false;
            return Paneles(panel);
        }

        public IActionResult PizarraCartera()
        {
            string? recID = HttpContext.Session.GetString("CIsesion");
            string? recTIT = HttpContext.Session.GetString("TITsesion");
            string rec = "";
            if (recID == null)
                recID = "-";
            if (recTIT == null)
                recTIT = "-";
            if (recID != "-")
                rec = recID;
            else
                rec = recTIT;
            List<ModeloCartera> creditos = STORED.DatosCartera(recID, recTIT);
            GetExtraCaja(rec);
            GetExtraRetencion(rec);
            return View(creditos);
        }

        public IActionResult PizarraCajas()
        {
            string? recID = HttpContext.Session.GetString("CIsesion");
            string? recTIT = HttpContext.Session.GetString("TITsesion");
            string rec = "";
            if (recID == null)
                recID = "-";
            if (recTIT == null)
                recTIT = "-";
            if (recID != "-")
                rec = recID;
            else
                rec = recTIT;
            List<ModeloCaja> cajas = STORED.DatosCajas(recID, recTIT);
            GetExtraCartera(rec);
            GetExtraCaja(rec);
            GetExtraRetencion(rec);
            List<(string, string)> barra = QUERY.GetBarraCAJA(rec);
            var categorias = new List<string>();
            var series = new List<Double>();
            foreach (var tuple in barra)
            {
                categorias.Add(tuple.Item1);
                series.Add(Double.Parse(tuple.Item2, CultureInfo.GetCultureInfo("en-US")));
            }
            ViewBag.CategoriasCaja = categorias;
            ViewBag.SeriesCaja = series;
            return View(cajas);
        }

        public IActionResult PizarraDpfs()
        {
            string? recID = HttpContext.Session.GetString("CIsesion");
            string? recTIT = HttpContext.Session.GetString("TITsesion");
            string rec = "";
            if (recID == null)
                recID = "-";
            if (recTIT == null)
                recTIT = "-";
            if (recID != "-")
                rec = recID;
            else
                rec = recTIT;
            List<ModeloDpf> dpfs = STORED.DatosDpf(recID, recTIT);
            GetExtraCaja(rec);
            GetExtraCartera(rec);
            GetExtraRetencion(rec);
            List<int> IdDpf = new List<int>();
            List<int> Faltantes = new List<int>();
            List<int> Completados = new List<int>();
            int c = 0;
            foreach (var dp in dpfs)
            {
                c++;
                IdDpf.Add(c);
                var apertura = dp.Fecha_de_Vencimiento.AddDays(-dp.Plazo);
                var comp = (int)(DateTime.Now - apertura).TotalDays;
                var falt = dp.Plazo - comp;
                Faltantes.Add(falt);
                Completados.Add(comp);

            }
            ViewBag.categoriasDPF = IdDpf;
            ViewBag.diasCDPF = Completados;
            ViewBag.diasFDPF = Faltantes;
            return View(dpfs);
        }

        public IActionResult PizarraTarjetas()
        {
            string? recID = HttpContext.Session.GetString("CIsesion");
            string? recTIT = HttpContext.Session.GetString("TITsesion");
            string rec = "";
            if (recID == null)
                recID = "-";
            if (recTIT == null)
                recTIT = "-";
            if (recID != "-")
                rec = recID;
            else
                rec = recTIT;
            ModeloTarjetas tarjetas = STORED.DatosTarjeta(recID, recTIT);
            GetExtraCaja(rec);
            GetExtraCartera(rec);
            GetExtraRetencion(rec);
            string vigven = tarjetas.Interes_Vigente_Bolivianos + "/" + tarjetas.Interes_Vencido_Bolivianos;
            ViewBag.interes = vigven;
            ViewBag.importe = tarjetas.Importe_Capital_Bolivianos;
            ViewBag.saldo = tarjetas.Saldo_Cartera_Bolivianos;
            ViewBag.tasa = tarjetas.Tasa;
            if (tarjetas.Fecha_de_incumplimiento.ToString() == "01/01/1999")
                ViewBag.Finc = "Sin fecha";
            else
                ViewBag.Finc = tarjetas.Fecha_de_incumplimiento.ToString("d/M/yyyy");
            if (tarjetas.Fecha_de_Vencimiento.ToString() == "01/01/1999")
                ViewBag.Venc = "Sin fecha";
            else
                ViewBag.Venc = tarjetas.Fecha_de_Vencimiento.ToString("d/M/yyyy");
            return View(tarjetas);
        }

        public IActionResult PizarraCorr()
        {
            string? recID = HttpContext.Session.GetString("CIsesion");
            string? recTIT = HttpContext.Session.GetString("TITsesion");
            string rec = "";
            if (recID == null)
                recID = "-";
            if (recTIT == null)
                recTIT = "-";
            if (recID != "-")
                rec = recID;
            else
                rec = recTIT;
            List<ModeloCorr> cuentas = STORED.DatosCuentas(recID, recTIT);
            GetExtraCaja(rec);
            GetExtraCartera(rec);
            GetExtraRetencion(rec);
            List<(string, string)> barra = QUERY.GetBarraCUENTAS(rec);
            var categorias = new List<string>();
            var series = new List<Double>();
            foreach (var tuple in barra)
            {
                categorias.Add(tuple.Item1);
                series.Add(Double.Parse(tuple.Item2, CultureInfo.GetCultureInfo("en-US")));
            }
            ViewBag.CategoriasCuentas = categorias;
            ViewBag.SeriesCuentas = series;
            return View(cuentas);
        }

        public IActionResult Regreso()
        {
            string? recID = HttpContext.Session.GetString("CIsesion");
            string? recTIT = HttpContext.Session.GetString("TITsesion");
            if (recID == null)
                recID = "-";
            if (recTIT == null)
                recTIT = "-";
            List<ModeloResumen> DATA = STORED.DatosCliente(recID, recTIT);
            _cache.Set("KeyPanel", DATA);
            return RedirectToAction("Paneles");
        }
    }
}

FichaCliente/Controllers/PeticionesController.cs
using Microsoft.AspNetCore.Mvc;
using FichaCliente.Models;
using FichaCliente.Scripts;

namespace FichaCliente.Controllers
{
    public class PeticionesController : Controller
    {
        Procedimientos DETALLES = new Procedimientos();
        Consultas COMBOX = new Consultas();

        [HttpPost]
        public JsonResult DetallesCartera(string operacionCRE)
        {
            ModeloCartera credito = DETALLES.DetalleCreditos(operacionCRE);
            return Json(new { respCre = credito });
        }

        [HttpGet]
        public JsonResult ComboCI()
        {
            List<string> docIdentidad = COMBOX.consultaDOC();
            return Json(new { combox = docIdentidad });
        }

        [HttpGet]
        public JsonResult ComboTIT()
        {
            List<string> nomTitular = COMBOX.consultaNOM();
            return Json(new { combox = nomTitular });
        }
    }
}

FichaCliente/Views/Fichas/PizarraCajas.cshtml
@model List<ModeloCaja>

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="es">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
    <link href="~/css/estilosficha.css" rel="stylesheet" />

    <script>
        $(document).ready(function () {
            var categorias = '@Html.Raw(Json.Serialize(ViewBag.CategoriasCaja))';
            var series = '@Html.Raw(Json.Serialize(ViewBag.SeriesCaja))';
            barraCAJAS(categorias, series);
        });

        function barraCAJAS(datos1, datos2) {
            var Categorias = JSON.parse(datos1);
            var Series = JSON.parse(datos2);
            Highcharts.chart('CAJAS', {
                chart: {
                    type: 'bar'
                },
                title: {
                    text: 'Gráfico por número de cuenta',
                    align: 'left'
                },
                xAxis: {
                    categories: Categorias,
                    title: {
                        text: null
                    }
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: 'Bs',
                        align: 'high'
                    },
                    labels: {
                        overflow: 'justify'
                    }
                },
                tooltip: {
                    valueSuffix: ' Bs',
                    formatter: function () {
                        return '<b>' + this.x + '</b><br/>' +
                            Highcharts.numberFormat(this.y, 2, ',', '.');
                    }
                },
                plotOptions: {
                    bar: {
                        dataLabels: {
                            enabled: true
                        }
                    }
                },
                series: [{
                    name: 'Saldo',
                    data: Series
                }]
            });
        }
    </script>

    <style>
        #CAJAS {
            height: 300px;
        }

        .or-eco {
            background-color: rgb(255,80,0);
            text-align: center;
            border: rgb(208, 208, 208) 2px solid;
        }
    </style>
</head>
<body>
    <header>
        <div class="container-fluid">
            <div class="row bg-eco">
                <div class="offset-4 col-4">
                    <h4 class="mt-3 text-center text-white">ECO - CLIENTE</h4>
                </div>
                <div class="col-4">
                    <a asp-controller="Fichas" asp-action="Regreso" class="btn mt-2 ind-eco float-end"><i class="bi bi-house"></i></a>
                </div>
            </div>
        </div>
    </header>
    <section>
        <div class="container">
            <div class="row mt-4">
                <div class="col-3">
                    <div class="row">
                        <label class="form-label">NOMBRE</label>
                        <textarea asp-for="@Model.ElementAt(0).Nombre_Cliente" class="form-control" rows="2" readonly></textarea>
                    </div>
                    <div class="row mt-2">
                        <label class="form-label">EDAD</label>
                        <input class="form-control" value="@ViewBag.edad" type="text" readonly />
                    </div>
                    <div class="row mt-2">
                        <label class="form-label">TELÉFONO/CELULAR</label>
                        <input class="form-control" type="text" value="@ViewBag.telefono" readonly />
                    </div>
                    <div class="row mt-2">
                        <label class="form-label">DIRECCIÓN</label>
                        <textarea rows="3" readonly class="form-control">@ViewBag.direccion</textarea>
                    </div>
                    <div class="row mt-2">
                        <label class="form-label">ANTIGÜEDAD</label>
                        <input asp-for="@Model.ElementAt(0).Fecha_de_Apertura" class="form-control" type="text" readonly asp-format="{0:dd/MM/yyyy}" />
                    </div>
                    <div class="row mt-2">
                        <label class="form-label">RETENCIONES JUDICIALES</label>
                        <input type="text" readonly class="form-control" value="@ViewBag.retenciones Bs" />
                    </div>
                </div>
                <div class="col-1">
                    <div class="barraV"></div>
                </div>
                <div class="col-8">
                    <div class="row">
                        <h2 style="color:rgb(255,80,0)">Caja de Ahorros</h2>
                        <div class="row barraH"></div>
                        <h4 class="mt-2">Saldo en Bs</h4>
                    </div>
                    <div class="row">
                        <figure class="highcharts-figure">
                            <div id="CAJAS"></div>
                        </figure>
                    </div>
                    <div class="row">
                        <h4>Detalle</h4>
                        <div class="table-responsive">
                            <table class="table table-bordered align-middle">
                                <thead class="or-eco text-white">
                                    <tr>
                                        <th><small>Cuenta</small></th>
                                        <th><small>Tipo</small></th>
                                        <th><small>Saldo</small></th>
                                        <th><small>Tasa</small></th>
                                        <th><small>Estado</small></th>
                                    </tr>
                                </thead>
                                <tbody style="border: rgb(208, 208, 208) 2px solid; text-align:center">
                                    @if (Model.FirstOrDefault() != null)
                                    {
                                        decimal SaldoTotal = 0;
                                        foreach (var campos in Model)
                                        {
                                            SaldoTotal += @campos.Saldo_en_Bolivianos;
                                            <tr>
                                                <td><small>@campos.Nro_de_Cuenta</small></td>
                                                <td><small>@campos.Tipo_de_Caja_de_Ahorro</small></td>
                                                <td><small>@String.Format("{0:n}",@Math.Round(campos.Saldo_en_Bolivianos,2))</small></td>
                                                <td><small>@campos.Tasa</small></td>
                                                <td><small>@campos.Estado</small></td>
                                            </tr>
                                        }
                                        <tr>
                                            <td></td>
                                            <td style="color:rgb(255,80,0);text-align:right;font-weight:bold">Total</td>
                                            <td>@String.Format("{0:n}",@Math.Round(SaldoTotal,2))</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

FichaCliente/Views/Fichas/PizarraCartera.cshtml
@model List<ModeloCartera>

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="es">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="~/css/estilosficha.css" rel="stylesheet" />

    <script>
        function datoCredito(OP) {
            $.ajax({
                url: '@Url.Action("DetallesCartera","Peticiones")',
                type: 'POST',
                data: { "operacionCRE": OP },
                success: function (data) {
                    $("#PRE").val(data.respCre.numero_de_Prestamo);
                    $("#PLA").val(data.respCre.plazo);
                    $("#DEST").val(data.respCre.destino);
                    $("#TIP").val(data.respCre.tipo_de_Credito);
                    var fecha = new Date(data.respCre.fecha_de_Vencimiento);
                    var fev = fecha.toLocaleDateString('es-ES');
                    $("#FEV").val(fev);
                    $("#DI").val(data.respCre.dias_de_Incumplimiento);
                    $("#CAL").val(data.respCre.calificacion);
                    $("#CAEDEC").text(data.respCre.caedeC_Prestamo);
                    $("#REP").val(data.respCre.cantidad_de_Reprogramaciones);
                    fecha = new Date(data.respCre.fecha_de_Reprogramaciones);
                    var ferep = fecha.toLocaleDateString('es-ES');
                    if (ferep == '1/1/1999') {
                        ferep = "Sin fecha";
                    }
                    $("#FEREP").val(ferep);
                    $("#DV").val(data.respCre.dias_de_Pase_a_Vencido);
                    $("#SEGDEV").val(data.respCre.tiene_seguro_de_Desgravamen);
                    $("#DetallesCartera").modal("show");
                }, error: function (response) {
                    console.log(response.responseText);
                }
            });
        }

        $(document).ready(function () {
            $(".cerrar").click(function () {
                $("#DetallesCartera").modal("hide");
            });
        });
    </script>
</head>
<body>
    <header>
        <div class="container-fluid">
            <div class="row bg-eco">
                <div class="offset-4 col-4">
                    <h4 class="mt-3 text-center text-white">ECO - CLIENTE</h4>
                </div>
                <div class="col-4">
                    <a asp-controller="Fichas" asp-action="Regreso" class="btn mt-2 ind-eco float-end"><i class="bi bi-house"></i></a>
                </div>
            </div>
        </div>
    </header>
    <section>
        <div class="container">
            <div class="row mt-4">
                <div class="col-3">
                    <div class="row">
                        <label class="form-label">NOMBRE</label>
                        <textarea asp-for="@Model.ElementAt(0).Nombre_Titular" class="form-control" rows="2" readonly></textarea>
                    </div>
                    <div class="row mt-2">
                        <label class="form-label">EDAD</label>
                        <input class="form-control" type="text" value="@ViewBag.edad" readonly />
                    </div>
                    <div class="row mt-2">
                        <label class="form-label">TELÉFONO/CELULAR</label>
                        <input asp-for="@Model.ElementAt(0).Nro_de_Celular" class="form-control" type="text" readonly />
                    </div>
                    <div class="row mt-2">
                        <label class="form-label">DIRECCIÓN</label>
                        <textarea asp-for="@Model.ElementAt(0).Direccion" rows="3" readonly class="form-control"></textarea>
                    </div>
                    <div class="row mt-2">
                        <label class="form-label">ANTIGÜEDAD</label>
                        <input class="form-control" type="text" value="@ViewBag.antiguedad" readonly />
                    </div>
                    <div class="row mt-2">
                        <label class="form-label">RETENCIONES JUDICIALES</label>
                        <input type="text" readonly class="form-control" value="@ViewBag.retenciones Bs" />
                    </div>
                </div>
                <div class="col-1">
                    <div class="barraV"></div>
                </div>
                <div class="col-8">
                    <div class="row">
                        <h2 style="color:rgb(255,80,0)">Créditos</h2>
                        <div class="row barraH"></div>
                        <h4 class="mt-2">Detalle</h4>
                    </div>
                    <div class="row mt-2 justify-content-between">
                        <div class="col">
                            @foreach (var prestamos in Model)
                            {
                                decimal Amor = @prestamos.Monto_Desembolsado_en_Bolivianos - @prestamos.Saldo_en_Bolivianos;
                                <button type="button" class="btn btn-secondary me-1" onclick="datoCredito(@prestamos.Numero_de_Prestamo)">
                                    <i class="bi bi-asterisk"></i> @prestamos.Numero_de_Prestamo
                                </button>
                                <div class="tasa-eco me-1">
                                    Tasa <span style="font-size:105%">@String.Format("{0:n}",@prestamos.Tasa)</span> %
                                </div>
                                <textarea rows="3" style="font-size:90%">Monto: @String.Format("{0:n}",@prestamos.Monto_Desembolsado_en_Bolivianos)
                                                    Saldo: @String.Format("{0:n}",@prestamos.Saldo_en_Bolivianos)
                                                    Amortizado: @String.Format("{0:n}",@Amor)
                                </textarea>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

<div class="modal fade" id="DetallesCartera" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-eco">
                <h5 class="modal-title text-white" id="Credito">Detalles de Crédito</h5>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-4">
                        <div class="input-group mt-3">
                            <span class="input-group-text">Plazo:</span>
                            <input class="form-control bg-white" type="text" id="PLA" readonly>
                        </div>
                        <div class="input-group mt-3">
                            <span class="input-group-text">Préstamo:</span>
                            <input class="form-control bg-white" type="text" id="PRE" readonly>
                        </div>
                        <div class="input-group mt-3">
                            <span class="input-group-text">Calificación:</span>
                            <input class="form-control bg-white" type="text" id="CAL" readonly>
                        </div>
                        <div class="input-group mt-3">
                            <span class="input-group-text">Días Vencido:</span>
                            <input class="form-control bg-white" type="text" id="DV" readonly>
                        </div>
                        <div class="input-group mt-3">
                            <span class="input-group-text" style="width:175px">Días Incumplimiento:</span>
                            <input class="form-control bg-white" type="text" id="DI" readonly>
                        </div>
                        <div class="input-group mt-3">
                            <span class="input-group-text" style="width:175px">Reprogramación:</span>
                            <input class="form-control bg-white" type="text" id="REP" readonly>
                        </div>
                        <div class="input-group mt-3">
                            <span class="input-group-text">Seguro Desgravamen:</span>
                            <input class="form-control bg-white" type="text" id="SEGDEV" readonly>
                        </div>
                    </div>
                    <div class="col-8">
                        <div class="input-group mt-3">
                            <span class="input-group-text">Tipo:</span>
                            <input class="form-control bg-white" type="text" id="TIP" readonly>
                        </div>
                        <div class="input-group mt-3">
                            <span class="input-group-text">Destino:</span>
                            <input class="form-control bg-white" type="text" id="DEST" readonly>
                        </div>
                        <div class="input-group mt-3">
                            <span class="input-group-text">CAEDEC:</span>
                            <textarea class="form-control bg-white" rows="3" id="CAEDEC" readonly></textarea>
                        </div>
                        <div class="input-group mt-3">
                            <span class="input-group-text" style="width:160px">Fecha Vencimiento:</span>
                            <input class="form-control bg-white" type="text" id="FEV" readonly>
                        </div>
                        <div class="input-group mt-3">
                            <span class="input-group-text">Fecha Reprogramación:</span>
                            <input class="form-control bg-white" type="text" id="FEREP" readonly>
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary cerrar" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>